---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    LOCATIONS_API_URL: https://refinery.nypl.org/api/nypl/locations/v1.0/locations
    KINESIS_BATCH_SIZE: 200
    BASE_SCHEMA_URL: https://platform.nypl.org/api/v0.1/current-schemas/
    REDSHIFT_DB_NAME: production
    LOG_LEVEL: info
ENCRYPTED_VARIABLES:
    HOURS_KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKgwgaUGCSqGSIb3DQEHBqCBlzCBlAIBADCBjgYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAybZILnKMur+bmDfXgCARCAYchX6UNE7+61+tcrQiw3+tUOFgLuqjq+kmYP8JHPajkRNjydXHp5/R6yD3iBOdTVXA282dBjJm6VH+8KklBqEt906uF09KtVFgx+BlE0+QND2NTbcTGvWEC7cDZeynfX2Uw=
    CLOSURE_ALERT_KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAK8wgawGCSqGSIb3DQEHBqCBnjCBmwIBADCBlQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxm2gJfPw+GRK7jdW4CARCAaO6ziShk91WKtOwA6M44WftAbzw6bZNhIPfaMh9j8oB/YRJhiduXWMR1yYAR7k4oYs8v43Qse3SgI2ICVMxTjODi9AkfvsClkHRzIBLF8a43iR8hWDnCV0hamRu5w1uuapkSDI6ct0k8
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHMwcQYJKoZIhvcNAQcGoGQwYgIBADBdBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC8BWmZkNuIiBd+zxwIBEIAwb+1L4oqHLpacTC09H1Rn0he/ZlW1iQvH0ES1v9J8mk29bux/RhjCLO44assvSDG1
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHEwbwYJKoZIhvcNAQcGoGIwYAIBADBbBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHe+zzEql8Er02e0eQIBEIAud9GTORlsHlAlQlm2H7aannlpHcoswwIwD799JoVBs7H52rWv81S04VwZRVhs/w==
...
