---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    KINESIS_BATCH_SIZE: 200
    BASE_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/
    REDSHIFT_DB_NAME: qa
    LOG_LEVEL: info
ENCRYPTED_VARIABLES:
    HOURS_KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwVpOczRCD6GEUVetQCARCAWzMfDEj3GgcOMxaPJLTiY8HhfArCJab8wsTJgB9Rh55S1wBAo/kXW9N7fFyfGAXctJddSWlCD5FaFPj6VJz9y7esPU9vhQFwmIT8NyUexdrpDqA+qFCAmBEJiRE=
    CLOSURE_ALERT_KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKkwgaYGCSqGSIb3DQEHBqCBmDCBlQIBADCBjwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAy7s5rSAh1WM5bMwVICARCAYvGQjDDR7dxY/LVc529IFWKQ3IqZaimIhJDZQebw+MZEo5wh5E0ZpvZFF042qRzE6ONWH0skMPz4Gp8A9YmNWwdvy7HAe5cLHTOrnSUwTOz0RvLz2UHaQPGwusZUHB4SLwzG
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHMwcQYJKoZIhvcNAQcGoGQwYgIBADBdBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC8BWmZkNuIiBd+zxwIBEIAwb+1L4oqHLpacTC09H1Rn0he/ZlW1iQvH0ES1v9J8mk29bux/RhjCLO44assvSDG1
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHEwbwYJKoZIhvcNAQcGoGIwYAIBADBbBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHe+zzEql8Er02e0eQIBEIAud9GTORlsHlAlQlm2H7aannlpHcoswwIwD799JoVBs7H52rWv81S04VwZRVhs/w==
...
