name: Deploy to production if tagged as production release

on:
  release:
    types: [ released ]
  
permissions:
  id-token: write
  contents: read

jobs:
  check_production_tags:
    name: Check the release tag
    runs-on: ubuntu-latest
    outputs:
      has_production_hours_tag: ${{ steps.check-production-hours-tag.outputs.output }}
      has_production_closure_alert_tag: ${{ steps.check-production-closure-alert-tag.outputs.output }}
    steps:
      - name: check production hours tag ${{ github.ref }}
        id: check-production-hours-tag
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/(production|production-hours)-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "output=true" >> $GITHUB_OUTPUT
          else
            echo "output=false" >> $GITHUB_OUTPUT
          fi
      - name: check production closure alert tag ${{ github.ref }}
        id: check-production-closure-alert-tag
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/(production|production-closure-alert)-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "output=true" >> $GITHUB_OUTPUT
          else
            echo "output=false" >> $GITHUB_OUTPUT
          fi
  publish_production:
    needs: [ check_production_tags ]
    if: needs.check_production_tags.outputs.has_production_hours_tag == 'true' || needs.check_production_tags.outputs.has_production_closure_alert_tag == 'true'
    name: Publish image to ECR and update ECS service(s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: location-hours-pollers
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:production-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:production-latest
      
      - name: Force ECS hours update
        if: needs.check_production_tags.outputs.has_production_hours_tag == 'true'
        run: |
          aws ecs update-service --cluster location-hours-poller-production --service location-hours-poller-production --force-new-deployment
      
      - name: Force ECS closure alert update
        if: needs.check_production_tags.outputs.has_production_closure_alert_tag == 'true'
        run: |
          aws ecs update-service --cluster location-closure-alert-poller-production --service location-closure-alert-poller-production --force-new-deployment
